<?php
/**
* @file joodb.php created 28.07.2011, 12:23:47
* @package		Joomla
* @author	feenders - dirk hoeschen (hoeschen@feenders.de)
* @abstract	custom component for client
* @link	http://www.feenders.de
* @copyright	Copyright (C) 2011 computer daten netze :: feenders
* @license		CC-GNU-LGPL
* @version  1.0
*/

// no direct access
defined('_JEXEC') or die('Restricted access');

class joodbModelJoodb extends JModelLegacy {
	
	/**
	 * Contructor
	 * @param array $config
	 */
	function __construct($config) {
		parent::__construct($config);
	}

	public function clean($group = null, $client_id = 0)
    {
        parent::cleanCache($group, $client_id); // TODO: Change the autogenerated stub
    }

}

